changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "## ⚠️ Breaking Changes"
      labels:
        - breaking-change
    - title: "## ✨ Features"
      labels:
        - feat
        - feature
    - title: "## 🐛 Bug Fixes"
      labels:
        - fix
        - bug
        - hotfix
    - title: "## 🔧 Other"
      labels:
        - chore
        - refactor
        - dep
        - ci
    - title: "## 📦 Uncategorized"
      labels:
        - "*"
