- uses: ardalanamini/auto-changelog@v4
  id  : changelog
  name: Changelog
  with:
    commit-types            : |
      feat    : New Features
      fix     : Bug Fixes
      build   : Build System & Dependencies
      perf    : Performance Improvements
      docs    : Documentation
      test    : Tests
      refactor: Refactors
      chore   : Chores
      ci      : CI
      style   : Code Style
      revert  : Reverts
    default-commit-type     : Other Changes
    release-name            : v2.0.2
